controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base2_to_link1
      - for_link2_2_to_link2
      - link2_to_link3
      - link3_to_link4
      - for_link5_1_to_link5
  - name: fake_robot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - for_link5_2_to_left_finger
      - for_link5_2_to_right_finger
initial:  # Define initial robot poses per group
#  - group: robot_arm
#    pose: home

  []