controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base2_to_link1
      - for_link2_2_to_link2
      - link2_to_link3
      - link3_to_link4
      - for_link5_1_to_link5
  - name: robot_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - for_link5_2_to_left_finger
      - for_link5_2_to_right_finger