# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base2_to_link1
    - for_link2_2_to_link2
    - link2_to_link3
    - link3_to_link4
    - for_link5_1_to_link5
    - for_link5_2_to_left_finger
    - for_link5_2_to_right_finger
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - base2_to_link1
    - for_link2_2_to_link2
    - link2_to_link3
    - link3_to_link4
    - for_link5_1_to_link5
  gains:
    base2_to_link1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    for_link2_2_to_link2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_to_link3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3_to_link4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    for_link5_1_to_link5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1