controller_list:
  - name: fake_robot_arm_controller
    type: $(arg execution_type)
    joints:
      - base_to_link1
      - for_link2_to_link2
      - link2_to_link3
      - link3_to_link4
      - for_link5_left_to_link5
  - name: fake_robot_hand_controller
    type: $(arg execution_type)
    joints:
      - link5_to_left_finger
      - link5_to_right_finger
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: start_arm
  - group: robot_hand
    pose: start_hand