# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_arm
  joint_model_group_pose: start_arm
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_to_link1
    - for_link2_to_link2
    - link2_to_link3
    - link3_to_link4
    - for_link5_left_to_link5
    - link5_to_left_finger
    - link5_to_right_finger
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controll:
  type: position_controllers/JointPositionController
  joints:
    - base_to_link1
    - for_link2_to_link2
    - link2_to_link3
    - link3_to_link4
    - for_link5_left_to_link5
  gains:
    base_to_link1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    for_link2_to_link2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_to_link3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3_to_link4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    for_link5_left_to_link5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1